[package]
name = "ekubo_oracle_extension"
version = "0.1.0"
description = "An geomean time weighted oracle extension for Ekubo Protocol"
homepage = "https://ekubo.org"
cairo-version = ">=2.7.0"
edition = '2024_07'

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }
starknet = ">=2.7.0"

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
casm = true

[lib]
allowed-libfuncs-list.name = "audited"

[[tool.snforge.fork]]
name = "mainnet"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/NiEYg24-vYIPZyy9tapT_cTsT8iGTkx-"
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "sepolia"
url = "https://free-rpc.nethermind.io/sepolia-juno"
block_id.tag = "Latest"

[dev-dependencies]
cairo_test = "2.8.0"
