[package]
name = "ekubo_extension"
version = "0.1.0"
description = "An extension for Ekubo Protocol"
homepage = "https://ekubo.org"
cairo-version = "2.6.3"
edition = '2023_11'

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry" }
starknet = "=2.6.3"

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
casm = true

[[tool.snforge.fork]]
name = "mainnet"
url = "https://rpc.nethermind.io/mainnet-juno/"
block_id.tag = "Latest"
